# Generated by Django 2.2.4 on 2019-09-21 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaddetails',
            old_name='phone_number',
            new_name='lead_stage',
        ),
        migrations.RemoveField(
            model_name='leaddetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='leaddetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='leaddetails',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='leaddetails',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='leaddetails',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='lead_source',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='lead_stage',
        ),
        migrations.AddField(
            model_name='leaddetails',
            name='lead_source',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fistname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('fk_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackapp.Company')),
                ('fk_created_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackapp.UserLogin')),
            ],
        ),
        migrations.AddField(
            model_name='leads',
            name='fk_consumer_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trackapp.Consumer'),
        ),
    ]
